//
//  UserModel.swift
//  Filmatch
//
//  Created by Daniel Enrique Almazán Sellés on 23/7/24.
//

import SwiftUI

struct UserModel: Sendable {
  let uuid: String
  let email: String
//  let birthdate: Date?
  let isAnonymous: Bool
  var image: URL?
  let providers: [FiltersStreamingProviderSingleResponse]

  static let `default` = UserModel(
    uuid: "1",
    email: "anaclet@secret.com",
//    birthdate: .now,
    isAnonymous: false,
    providers: [
      FiltersStreamingProviderSingleResponse(
        providerId: 8, providerName: "Netflix",
        logoPath: "/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg", displayPriority: 5,
        displayPriorities: [
          "AE": 0,
          "AD": 0,
          "AG": 0,
          "AL": 0,
          "AO": 4,
          "AR": 1,
          "AT": 0,
          "AU": 1,
          "AZ": 2,
          "BA": 0,
          "BB": 0,
          "BE": 1,
          "BG": 0,
          "BH": 0,
          "BM": 0,
          "BO": 0,
          "BR": 2,
          "BS": 0,
          "BY": 6,
          "BZ": 7,
          "CA": 0,
          "CH": 0,
          "CI": 0,
          "CL": 2,
          "CO": 2,
          "CM": 4,
          "CR": 0,
          "CU": 0,
          "CV": 0,
          "CZ": 1,
          "CY": 7,
          "DE": 0,
          "DK": 1,
          "DO": 0,
          "DZ": 0,
          "EC": 0,
          "EE": 0,
          "EG": 0,
          "ES": 6,
          "FI": 1,
          "FJ": 0,
          "FR": 1,
          "GB": 0,
          "GF": 0,
          "GG": 0,
          "GH": 0,
          "GI": 0,
          "GQ": 0,
          "GR": 0,
          "GT": 0,
          "HK": 1,
          "HN": 0,
          "HR": 0,
          "HU": 1,
          "ID": 0,
          "IE": 0,
          "IL": 0,
          "IN": 0,
          "IQ": 0,
          "IT": 1,
          "IS": 0,
          "JM": 0,
          "JP": 0,
          "JO": 0,
          "KE": 0,
          "KR": 0,
          "KW": 0,
          "LB": 0,
          "LC": 0,
          "LI": 0,
          "LT": 0,
          "LU": 8,
          "MA": 0,
          "LV": 0,
          "LY": 0,
          "MC": 0,
          "ME": 4,
          "MD": 0,
          "MG": 4,
          "MK": 0,
          "MT": 0,
          "ML": 5,
          "MU": 0,
          "MX": 8,
          "MZ": 0,
          "MY": 1,
          "NE": 0,
          "NG": 0,
          "NL": 0,
          "NI": 11,
          "NO": 1,
          "NZ": 1,
          "OM": 0,
          "PA": 0,
          "PE": 2,
          "PK": 0,
          "PF": 0,
          "PL": 1,
          "PH": 0,
          "PS": 0,
          "PT": 1,
          "PY": 0,
          "QA": 0,
          "RO": 1,
          "RS": 0,
          "SA": 0,
          "SC": 0,
          "SI": 0,
          "SG": 0,
          "SE": 1,
          "SN": 0,
          "SV": 0,
          "SK": 1,
          "SM": 0,
          "TC": 0,
          "TH": 1,
          "TD": 5,
          "TN": 0,
          "TR": 1,
          "TT": 0,
          "TW": 0,
          "TZ": 0,
          "UA": 0,
          "UG": 0,
          "US": 7,
          "UY": 0,
          "VE": 0,
          "YE": 0,
          "ZA": 0,
          "ZM": 0,
          "ZW": 5,
        ]),
      FiltersStreamingProviderSingleResponse(
        providerId: 337, providerName: "Disney Plus",
        logoPath: "/97yvRBw1GzX7fXprcF80er19ot.jpg", displayPriority: 28,
        displayPriorities: [
          "AD": 7,
          "AL": 7,
          "AR": 0,
          "AT": 2,
          "AU": 0,
          "BA": 7,
          "BE": 0,
          "BG": 16,
          "BO": 2,
          "BR": 0,
          "BZ": 2,
          "CA": 1,
          "CH": 2,
          "CL": 0,
          "CO": 0,
          "CR": 2,
          "CZ": 0,
          "DK": 0,
          "DE": 2,
          "DO": 25,
          "EC": 1,
          "EE": 23,
          "ES": 1,
          "FI": 0,
          "EG": 46,
          "FR": 0,
          "GB": 1,
          "GT": 1,
          "GR": 20,
          "HN": 2,
          "HU": 0,
          "HK": 33,
          "HR": 32,
          "IE": 2,
          "IT": 0,
          "IS": 1,
          "JP": 3,
          "JM": 27,
          "KR": 2,
          "LC": 14,
          "LU": 3,
          "LI": 26,
          "LT": 24,
          "LV": 23,
          "ME": 1,
          "MK": 7,
          "MT": 7,
          "MX": 0,
          "NI": 2,
          "NL": 1,
          "NO": 0,
          "NZ": 0,
          "PE": 0,
          "PA": 28,
          "PL": 0,
          "PT": 0,
          "PH": 31,
          "PY": 2,
          "RO": 0,
          "RS": 7,
          "SG": 2,
          "SI": 7,
          "SE": 0,
          "SK": 0,
          "SV": 28,
          "SM": 26,
          "TR": 9,
          "TT": 15,
          "TW": 2,
          "US": 0,
          "VE": 1,
          "UY": 28,
        ]),
    ])
}
